export const vaultDesignTokens = {
  colors: {
    brand: {
      purple: "#6c5ce7",
      navy: "#1a1a2e",
      navyHover: "#2a2a4e",
      gold: "#f0c040",
      white: "#ffffff",
    },
    text: {
      primary: "#101828",
      secondary: "#6a7282",
      tertiary: "#99a1af",
      body: "#364153",
      onDark1: "#ffffff",
      onDark2: "#99a1af",
      onDark3: "#d1d5dc",
    },
    surface: {
      appBg: "#f4f6fc",
      contentBg: "#ffffff",
      sidebarBg: "#1a1a2e",
      cardBorder: "#e5e7eb",
      dividerLight: "#f3f4f6",
      mutedBg: "#f9fafb",
      overlayBg: "rgba(26, 26, 46, 0.45)",
    },
    status: {
      todo: "#6b7280",
      inProgress: "#2563eb",
      inReview: "#7c3aed",
      done: "#16a34a",
      blocked: "#d4183d",
      askBoss: "#f0c040",
      ready: "#4a5565",
      toQualify: "#9ca3af",
      backlog: "#6b7280",
    },
    feedback: {
      destructive: "#d4183d",
    },
  },
  typography: {
    fontSans: '"Arimo", "IBM Plex Sans", "Segoe UI", sans-serif',
    fontMono: '"Cousine", "IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    pill: 9999,
  },
  layout: {
    sidebarWidth: 240,
  },
  shadow: {
    modal: "0 24px 48px rgba(16, 24, 40, 0.2)",
    card: "0 1px 2px rgba(16, 24, 40, 0.05)",
  },
} as const;

type CssVarMap = Record<`--${string}`, string>;

export const vaultCssVariables: CssVarMap = {
  "--vault-color-brand-purple": vaultDesignTokens.colors.brand.purple,
  "--vault-color-brand-navy": vaultDesignTokens.colors.brand.navy,
  "--vault-color-brand-gold": vaultDesignTokens.colors.brand.gold,
  "--vault-color-text-primary": vaultDesignTokens.colors.text.primary,
  "--vault-color-text-secondary": vaultDesignTokens.colors.text.secondary,
  "--vault-color-text-tertiary": vaultDesignTokens.colors.text.tertiary,
  "--vault-color-text-on-dark1": vaultDesignTokens.colors.text.onDark1,
  "--vault-color-text-on-dark2": vaultDesignTokens.colors.text.onDark2,
  "--vault-color-text-on-dark3": vaultDesignTokens.colors.text.onDark3,
  "--vault-color-surface-app": vaultDesignTokens.colors.surface.appBg,
  "--vault-color-surface-content": vaultDesignTokens.colors.surface.contentBg,
  "--vault-color-surface-sidebar": vaultDesignTokens.colors.surface.sidebarBg,
  "--vault-color-surface-border": vaultDesignTokens.colors.surface.cardBorder,
  "--vault-color-surface-divider": vaultDesignTokens.colors.surface.dividerLight,
  "--vault-color-surface-muted": vaultDesignTokens.colors.surface.mutedBg,
  "--vault-color-surface-overlay": vaultDesignTokens.colors.surface.overlayBg,
  "--vault-color-status-backlog": vaultDesignTokens.colors.status.backlog,
  "--vault-color-status-to-qualify": vaultDesignTokens.colors.status.toQualify,
  "--vault-color-status-ready": vaultDesignTokens.colors.status.ready,
  "--vault-color-status-in-progress": vaultDesignTokens.colors.status.inProgress,
  "--vault-color-status-in-review": vaultDesignTokens.colors.status.inReview,
  "--vault-color-status-blocked": vaultDesignTokens.colors.status.blocked,
  "--vault-color-status-ask-boss": vaultDesignTokens.colors.status.askBoss,
  "--vault-color-status-done": vaultDesignTokens.colors.status.done,
  "--vault-font-sans": vaultDesignTokens.typography.fontSans,
  "--vault-font-mono": vaultDesignTokens.typography.fontMono,
  "--vault-radius-sm": `${vaultDesignTokens.radius.sm}px`,
  "--vault-radius-md": `${vaultDesignTokens.radius.md}px`,
  "--vault-radius-lg": `${vaultDesignTokens.radius.lg}px`,
  "--vault-radius-pill": `${vaultDesignTokens.radius.pill}px`,
  "--vault-space-xs": `${vaultDesignTokens.spacing.xs}px`,
  "--vault-space-sm": `${vaultDesignTokens.spacing.sm}px`,
  "--vault-space-md": `${vaultDesignTokens.spacing.md}px`,
  "--vault-space-lg": `${vaultDesignTokens.spacing.lg}px`,
  "--vault-space-xl": `${vaultDesignTokens.spacing.xl}px`,
  "--vault-space-xxl": `${vaultDesignTokens.spacing.xxl}px`,
  "--vault-layout-sidebar-width": `${vaultDesignTokens.layout.sidebarWidth}px`,
};
